# Generated by Django 3.0.2 on 2020-01-03 17:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('desc', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='course/%Y/%m')),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='course/thumb/%Y/%m')),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('is_section', models.BooleanField(default=False)),
                ('datetime_publish', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('datetime_update', models.DateTimeField(auto_now=True, db_index=True)),
                ('datetime_create', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='project.Project')),
            ],
            options={
                'verbose_name': 'course.course',
                'ordering': ['-datetime_update'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort', models.IntegerField(db_index=True, default=1)),
                ('datetime_update', models.DateTimeField(auto_now=True, db_index=True)),
                ('datetime_create', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
            options={
                'verbose_name': 'course.section',
                'ordering': ['sort'],
            },
        ),
    ]
