# Generated by Django 3.0.2 on 2020-01-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='sort',
            field=models.SmallIntegerField(db_index=True, default=1),
        ),
    ]
