# Generated by Django 3.0.2 on 2020-01-03 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_content_id', models.IntegerField()),
                ('content_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('sort', models.SmallIntegerField(db_index=True, default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('datetime_update', models.DateTimeField(auto_now=True, db_index=True)),
                ('datetime_create', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType')),
                ('parent_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='project.Project')),
            ],
            options={
                'ordering': ['sort'],
                'index_together': {('parent_content_type', 'parent_content_id', 'sort', 'is_active')},
            },
        ),
    ]
