# Generated by Django 3.0.2 on 2020-01-03 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streaming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(1, 'Opencast')], default=1)),
                ('url', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('usage', models.FloatField(default=0.0)),
                ('size', models.FloatField(default=0.0)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('datetime_create', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='project.Project')),
            ],
            options={
                'ordering': ['-datetime_create'],
            },
        ),
    ]
