# Generated by Django 3.0.2 on 2020-01-03 18:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='video/%Y/%m')),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='video/thumb/%Y/%m')),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('uuid', models.CharField(db_index=True, max_length=120)),
                ('path', models.CharField(db_index=True, max_length=255)),
                ('status', models.SmallIntegerField(choices=[(0, 'init'), (1, 'uploading'), (2, 'waiting'), (3, 'processing'), (4, 'completed')], default=0)),
                ('datetime_create', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='project.Project')),
                ('streaming', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='streaming.Streaming')),
            ],
            options={
                'verbose_name': 'video.video',
                'ordering': ['-datetime_create'],
            },
        ),
    ]
